C=============================================================== ADDITIO
C**** ADDITIM
C
      INTEGER*4      NDISKDM,NFURESM,NMACHIM,NMEMOM,ICHAL
C
      COMMON/ADDITIM/NDISKDM,NFURESM,NMACHIM,NMEMOM,ICHAL
C
      INTEGER*4       NMEMO1M,NMEMO2M,NMEMO3M,NMEMO4M,NMEMO5M
      COMMON/ADDITI1M/NMEMO1M,NMEMO2M,NMEMO3M,NMEMO4M,NMEMO5M
C
      INTEGER*4       NMEMO6M,NMEMO7M,NMEMO8M,NMEMO9M,NMEMO10M
      COMMON/ADDITI2M/NMEMO6M,NMEMO7M,NMEMO8M,NMEMO9M,NMEMO10M
C
      INTEGER*4       NMEMO11M,NMEMO12M,NMEMO13M,NMEMO14M,NMEMO15M
      COMMON/ADDITI3M/NMEMO11M,NMEMO12M,NMEMO13M,NMEMO14M,NMEMO15M
C
      INTEGER*4       NMEMO16M,NMEMO17M,NMEMO18M,NMEMO19M,NMEMO20M
      COMMON/ADDITI4M/NMEMO16M,NMEMO17M,NMEMO18M,NMEMO19M,NMEMO20M
C
C=============================================================== ADDITIO
