#!/bin/bash

source $HOME/PETSC/patch_utils_conf.sh

if [ ! -e cvsroot.$local ] 
    then echo "cvsroot.$local doesn't exist!!";
    exit 0;
fi

echo "Tarring cvsroot.$local..."
tar czvf cvsroot.$local.tgz cvsroot.$local

if [ ! -f cvsroot.patch ]
    then echo "cvsroot.patch doesn't exist!!";
fi

echo -n "Apply patch ? (y/n) > "
read answer
if [ ! "$answer" = "y" ] 
    then exit 1
fi

echo "Applying patch ..."
pushd cvsroot.$local 
patch -E -p1 < ../cvsroot.patch
popd

if [ -d cvsroot.$remote ]
    then echo -n "Remove cvsroot.$remote  ? (y/n) > "
    read answer
    if [ ! "$answer" = "y" ] 
	then exit 1
    fi
    rm -rf cvsroot.$remote
fi

echo "Moving cvsroot.$local to cvsroot.$remote"
mv -f cvsroot.$local cvsroot.$remote

echo -n "Tar cvsroot.$remote  ? (y/n) > "
read answer
if [ ! "$answer" = "y" ] 
    then exit 1
fi

echo "Tarring cvsroot.$remote..."
tar czvf cvsroot.$remote.tgz cvsroot.$remote

echo "Moving cvsroot.$remote to cvsroot"
mv -f cvsroot.$remote cvsroot

pushd PETSC
if [ -d petscfem.old ] 
    then echo -n "Remove petscfem.old  ? (y/n) > "
    read answer
    if [ ! "$answer" = "y" ] 
	then exit 1
    fi
    rm -rf petscfem.old
fi

if [ -d petscfem ]
then echo "Moving petscfem to petscfem.old"
    mv petscfem petscfem.old
fi

echo -n "Check out petscfem  ? (y/n) > "
read answer
if [ ! "$answer" = "y" ] 
    then exit 1
fi

echo "Checking out petscfem..."
cvs co petscfem

echo -n "Make '\$ make sw'  ? (y/n) > "
read answer
if [ ! "$answer" = "y" ] 
    then exit 1
fi

echo "Making '\$ make sw' ..."
pushd petscfem
make sw

#popd
#popd
