#!/usr/bin/perl

use Parse::ePerl;
$script_in=shift();
open SCRIPT,$script_in;
$script = join("",(<SCRIPT>));
close SCRIPT;
#$script = join("",(<STDIN>));

Parse::ePerl::Translate({
    Script => $script,
    Result => \$script,
});

#print $script;

Parse::ePerl::Evaluate({
    Script => $script,
    Result => \$script,
});

print $script;
