#!/usr/bin/perl

use Getopt::Std;
getopts("mh");

sub give_help {
/'/;
    print <<EOM;
Selects a number of processors from a processor table. 
usage: procsel [OPTIONS] proctable
options: -h          give help
         -m <file>   file to write the list of processors (to be used by MPI)
                      default: ./machi.dat
         -w <file>   file to write the weights of processors (to be used by PETSc-FEM) 
                      default: ./weights.dat
EOM
/'/;
exit;
}

give_help if ($opt_h) ;

$proct = shift();
$machi = $opt_m;
$machi = "machi.dat" unless $machi;

$weights = $opt_w;
$weights = "weights.dat" unless $weights;

open PROCT,"$proct" || die "can't open file $proct\n";
open MACHI,">$machi" || die "can't open file $machi\n";
open WEIGHTS,">$weights" || die "can't open file $weights\n";

$nproc=0;
while (<PROCT>) {
    s/\#.*$//;      # discard  comments
    next if /^\s*$/; # discard empty lines
    ($proc,$w) = m/(\S*)\s*(\S*)/;
    $nproc++;
    print MACHI "$proc\n";
    # We print also the processor name in the weights table, but this is redundant 
    print WEIGHTS "$w  $proc\n";
}
close PROCT;
close MACHI;
close WEIGHTS;
