#!/usr/bin/perl
#__INSERT_LICENSE__
#$Id: makeltag,v 1.14 2004/05/22 13:46:21 mstorti Exp $

sub ask {
    my $ans;
    my $text = shift();
    print "$text (y/n [default y]) > ";
    $ans = <STDIN>;
    chomp $ans;
    die "Aborting... \n" if $ans =~ /n/i;
}

## usage: insertbef <text>, <file>, <regexp>,<skip>;
## Insert <text> in <file> before line containing <regexp>. 
## If <skip> is true then insert <text> before all blank lines prior
## to regexp. 
sub insertbef {
    my ($text,$file,$pos_rgxp,$skip) = @_;
    rename $file, "$file~";
    open FOLD,"$file~";
    open FNEW,">$file";
    my @queue = ();
    while (<FOLD>) {
	if (/^\s*$/) { push @queue; next; }
	else {
	    print FNEW "$text\n" if /^$pos_rgxp/;
	    print FNEW @queue;
	    @queue = ();
	    print FNEW;
	}
    }
    close FNEW;
    close FOLD;
}

$save_log = shift();
$notes = shift();
$tmp = "./tmp_file_log.txt.tmp";

system "echo n | cvs rel .";
ask "\nContinue ? ";
$|=1;

open SVL,"$save_log";
print "Last tags :\n";
@svl=();
my $use_pl = 0;
while (<SVL>) {
    push @svl,$_ if /^tag/;
    if (/^tag:\s*(\S*\.\S*\.)(pl)?(\d*)/) {
	($last_tag,$pl_flag,$pl) = ($1,$2,$3);
	if ($pl_flag eq 'pl') { $use_pl = 1; }
	else { $use_pl = 0; }
    } elsif (/^tag:\s*(\S*)\s/) {
	$last_tag = $1.".";
	$pl = 0;
    }
}
close SVL;
$n = $#svl-10;
$n = 0 if $n<0;
for ($j=$n; $j<=$#svl; $j++) { print $svl[$j]; }

$new_tag = $last_tag.($use_pl ? "pl" : "").($pl+1);
print "Enter new tag: [def $new_tag]> ";
$newtag = <STDIN>;
chomp $newtag;
if (! $newtag) {
    $newtag = $new_tag;
}
$newtag_ = $newtag;
$newtag =~ s/\-/--/g; 
$newtag =~ s/\./-/g;

print "Encoded tag \"$newtag\"\n";
my $pl_flag = ($use_pl ? '-p' : '-P');
system "./tools/checktag -l $pl_flag $newtag_ ./save.log";
ask "\nContinue ? ";

print "Now I will launch the editor in order\n",
    "    to enter a log message for this release...\n",
    "    <press enter to continue>\n";
<STDIN>;
system "\$EDITOR $tmp";

open SVL,">>$save_log";
print SVL "----------\n"; # >> $savelog;
$d = `date --rfc-822`;
chomp $d;
$w = `whoami`;
chomp $w;
$h = `hostname -f`;
chomp $h;
print SVL "tag: $newtag_ on $d by $w in $h\n";
open TMP,"$tmp";
while (<TMP>) {
    print SVL "     > $_";
}
close TMP;
if ( -f $tmp) {
    unlink $tmp;
}

# system "cat $tmp >>save.log";
close SVL;

# Insert a tag in `notes' file
insertbef "----------\n[tag: $newtag_ on $d by $w in $h]\n",
    $notes, ".*Current line ===========" if $notes;

open VRS,">VERSION";
print VRS $newtag_;
close VRS;

print "logging on $save_log\n";

system "cvs ci -m \"Administrative files\" notes.txt save.log VERSION";
