#!/bin/bash
#__INSERT_LICENSE__
#$Id: pfcpp,v 1.5 2004/09/25 16:57:57 mstorti Exp $

TMP=./pfcpp_temp.cpp

cat > $TMP

g++ -C -E						    \
    -I$PETSCFEM_DIR					    \
    -I$HOME/PETSC/petsc-2.0.24/include			    \
    -I$HOME/PETSC/petsc-2.0.24/bmake/linux		    \
    -I/usr/local/mpi/include -I/usr/lib/glib/include	    \
    -I/usr/include/glib-1.2				    \
    -I$HOME/SOFT/NEWMAT/src -I$HOME/SOFT/metis-4.0/Lib	    \
    -I../src -I$HOME/SOFT/meschach-1.2 -I/usr/local/include \
    -I$HOME/PETSC/ann_0.2/include			    \
    -I$PETSCFEM_DIR/src					    \
    -I$HOME/SOFT/SuperLU				    \
    $TMP
